### ISSUE TITLE
Fix category from slug

### ISSUE THREAD

**Issue by igordsm** [insper-education/devlife-support-api#44]
The directory structure change in `devlife-content`. Adapt UI and backend code.

**Comment by toshikurauchi** [comment]
- [X] `devlife-content` ([PR 330](https://github.com/insper-education/devlife-content/pull/330))
- [ ] `devlife-vscode-plugin`
- [ ] `devlife-support-api`

**Comment by toshikurauchi** [comment]
The class name is currently displayed like this after updating `devlife-content`:

![image](https://user-images.githubusercontent.com/219816/142333846-0385aa4b-5e3f-4919-8305-52af5bbc61f1.png)

It looks ok to me. Do you think we can consider it fixed in `devlife-support-api`, @igordsm?
