### ISSUE TITLE
List students submissions 

### ISSUE THREAD

**Issue by cicerotcv** [insper-education/devlife-support-api#61]
It seems not to be necessary to use `ans_pk` in these endpoints

https://github.com/insper-education/devlife-support-api/blob/79279f36be407aedb8ae2ff0518e7f7d0603bac4/core/urls.py#L15-L16

**Comment by toshikurauchi** [comment]
@cicerotcv you're right. It doesn't make sense to ask for a answer id when we are listing many answers.
